version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: "hackmongo"
    environment:
      - MONGO_DATA_DIR=/mongodb-data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongodb-data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
