// data-model.js - A mongoose model
//
// See http://mongoosejs.com/docs/models.html
// for more of what you can do here.
module.exports = function(app) {
  const mongooseClient = app.get('mongooseClient')
  const { Schema } = mongooseClient
  const data = new Schema(
    {
      Personalnummer: { type: Number },
      Name: { type: String },
      Geburtstag: { type: Date },
      Bestandsart: { type: Date },
      Geschlecht: { type: Number },
      Standort: { type: String },
      'Eintritt/Rentenbeginn': { type: Date },
      'Beginn vers f Dienstzeit': { type: Date },
      Zusagedatum: { type: Date },
      Endalter: { type: Number },
      'PR - DBO': { type: Number },
      'PR - Current Service Cost': { type: Number },
      'PR - DBO Zins+': { type: Number },
      'PR - DBO Zins-': { type: Number },
      'PR - Zahlung 2019': { type: Number },
      'PR - Zahlung 2020': { type: Number },
      'PR - Zahlung 2021': { type: Number },
      'PR - Zahlung 2022': { type: Number },
      'PR - Zahlung 2023': { type: Number },
      'PR_Sonder1 - DBO': { type: Number },
      'PR_Sonder1 - Current Service Cost': { type: Number },
      'PR_Sonder1 - DBO Zins+': { type: Number },
      'PR_Sonder1 - DBO Zins-': { type: Number },
      'PR_Sonder1 - Zahlung 2019': { type: Number },
      'PR_Sonder1 - Zahlung 2020': { type: Number },
      'PR_Sonder1 - Zahlung 2021': { type: Number },
      'PR_Sonder1 - Zahlung 2022': { type: Number },
      'PR_Sonder1 - Zahlung 2023': { type: Number },
      'PR_Sonder2 - DBO': { type: Number },
      'PR_Sonder2 - Current Service Cost': { type: Number },
      'PR_Sonder2 - DBO Zins+': { type: Number },
      'PR_Sonder2 - DBO Zins-': { type: Number },
      'PR_Sonder2 - Zahlung 2019': { type: Number },
      'PR_Sonder2 - Zahlung 2020': { type: Number },
      'PR_Sonder2 - Zahlung 2021': { type: Number },
      'PR_Sonder2 - Zahlung 2022': { type: Number },
      'PR_Sonder2 - Zahlung 2023': { type: Number },
      'UK - DBO': { type: Number },
      'UK - Current Service Cost': { type: Number },
      'UK - DBO Zins+': { type: Number },
      'UK - DBO Zins-': { type: Number },
      'UK - Zahlung 2019': { type: Number },
      'UK - Zahlung 2020': { type: Number },
      'UK - Zahlung 2021': { type: Number },
      'UK - Zahlung 2022': { type: Number },
      'UK - Zahlung 2023': { type: Number },
      'DC_neu - DBO': { type: Number },
      'DC_neu - Current Service Cost': { type: Number },
      'DC_neu - Umwandlung': { type: Number },
      'DC_neu - DBO Zins+': { type: Number },
      'DC_neu - DBO Zins-': { type: Number },
      'DC_neu - Zahlung 2019': { type: Number },
      'DC_neu - Zahlung 2020': { type: Number },
      'DC_neu - Zahlung 2021': { type: Number },
      'DC_neu - Zahlung 2022': { type: Number },
      'DC_neu - Zahlung 2023': { type: Number },
      'DC_alt - DBO': { type: Number },
      'DC_alt - Current Service Cost': { type: Number },
      'DC_alt - Umwandlung': { type: Number },
      'DC_alt - DBO Zins+': { type: Number },
      'DC_alt - DBO Zins-': { type: Number },
      'DC_alt - Zahlung 2019': { type: Number },
      'DC_alt - Zahlung 2020': { type: Number },
      'DC_alt - Zahlung 2021': { type: Number },
      'DC_alt - Zahlung 2022': { type: Number },
      'DC_alt - Zahlung 2023': { type: Number },
      'DC_Exec - DBO': { type: Number },
      'DC_Exec - Current Service Cost': { type: Number },
      'DC_Exec - Umwandlung': { type: Number },
      'DC_Exec - DBO Zins+': { type: Number },
      'DC_Exec - DBO Zins-': { type: Number },
      'DC_Exec - Zahlung 2019': { type: Number },
      'DC_Exec - Zahlung 2020': { type: Number },
      'DC_Exec - Zahlung 2021': { type: Number },
      'DC_Exec - Zahlung 2022': { type: Number },
      'DC_Exec - Zahlung 2023': { type: Number },
      'DC_Sonder1 - DBO': { type: Number },
      'DC_Sonder1 - Current Service Cost': { type: Number },
      'DC_Sonder1 - Umwandlung': { type: Number },
      'DC_Sonder1 - DBO Zins+': { type: Number },
      'DC_Sonder1 - DBO Zins-': { type: Number },
      'DC_Sonder1 - Zahlung 2019': { type: Number },
      'DC_Sonder1 - Zahlung 2020': { type: Number },
      'DC_Sonder1 - Zahlung 2021': { type: Number },
      'DC_Sonder1 - Zahlung 2022': { type: Number },
      'DC_Sonder1 - Zahlung 2023': { type: Number },
      'DC_Sonder2 - DBO': { type: Number },
      'DC_Sonder2 - Current Service Cost': { type: Number },
      'DC_Sonder2 - Umwandlung': { type: Number },
      'DC_Sonder2 - DBO Zins+': { type: Number },
      'DC_Sonder2 - DBO Zins-': { type: Number },
      'DC_Sonder2 - Zahlung 2019': { type: Number },
      'DC_Sonder2 - Zahlung 2020': { type: Number },
      'DC_Sonder2 - Zahlung 2021': { type: Number },
      'DC_Sonder2 - Zahlung 2022': { type: Number },
      'DC_Sonder2 - Zahlung 2023': { type: Number },
      'DC_Sonder3 - DBO': { type: Number },
      'DC_Sonder3 - Current Service Cost': { type: Number },
      'DC_Sonder3 - Umwandlung': { type: Number },
      'DC_Sonder3 - DBO Zins+': { type: Number },
      'DC_Sonder3 - DBO Zins-': { type: Number },
      'DC_Sonder3 - Zahlung 2019': { type: Number },
      'DC_Sonder3 - Zahlung 2020': { type: Number },
      'DC_Sonder3 - Zahlung 2021': { type: Number },
      'DC_Sonder3 - Zahlung 2022': { type: Number },
      'DC_Sonder3 - Zahlung 2023': { type: Number },
      'DC_Sonder4 - DBO': { type: Number },
      'DC_Sonder4 - Current Service Cost': { type: Number },
      'DC_Sonder4 - Umwandlung': { type: Number },
      'DC_Sonder4 - DBO Zins+': { type: Number },
      'DC_Sonder4 - DBO Zins-': { type: Number },
      'DC_Sonder4 - Zahlung 2019': { type: Number },
      'DC_Sonder4 - Zahlung 2020': { type: Number },
      'DC_Sonder4 - Zahlung 2021': { type: Number },
      'DC_Sonder4 - Zahlung 2022': { type: Number },
      'DC_Sonder4 - Zahlung 2023': { type: Number },
      'DC_Sonder5 - DBO': { type: Number },
      'DC_Sonder5 - Current Service Cost': { type: Number },
      'DC_Sonder5 - Umwandlung': { type: Number },
      'DC_Sonder5 - DBO Zins+': { type: Number },
      'DC_Sonder5 - DBO Zins-': { type: Number },
      'DC_Sonder5 - Zahlung 2019': { type: Number },
      'DC_Sonder5 - Zahlung 2020': { type: Number },
      'DC_Sonder5 - Zahlung 2021': { type: Number },
      'DC_Sonder5 - Zahlung 2022': { type: Number },
      'DC_Sonder5 - Zahlung 2023': { type: Number },
      'DC_Sonder6 - DBO': { type: Number },
      'DC_Sonder6 - Current Service Cost': { type: Number },
      'DC_Sonder6 - Umwandlung': { type: Number },
      'DC_Sonder6 - DBO Zins+': { type: Number },
      'DC_Sonder6 - DBO Zins-': { type: Number },
      'DC_Sonder6 - Zahlung 2019': { type: Number },
      'DC_Sonder6 - Zahlung 2020': { type: Number },
      'DC_Sonder6 - Zahlung 2021': { type: Number },
      'DC_Sonder6 - Zahlung 2022': { type: Number },
      'DC_Sonder6 - Zahlung 2023': { type: Number },
      'DC_Sonder7 - DBO': { type: Number },
      'DC_Sonder7 - Current Service Cost': { type: Number },
      'DC_Sonder7 - Umwandlung': { type: Number },
      'DC_Sonder7 - DBO Zins+': { type: Number },
      'DC_Sonder7 - DBO Zins-': { type: Number },
      'DC_Sonder7 - Zahlung 2019': { type: Number },
      'DC_Sonder7 - Zahlung 2020': { type: Number },
      'DC_Sonder7 - Zahlung 2021': { type: Number },
      'DC_Sonder7 - Zahlung 2022': { type: Number },
      'DC_Sonder7 - Zahlung 2023': { type: Number },
      Alter: { type: Number }
    },
    {
      timestamps: true
    }
  )

  return mongooseClient.model('data', data)
}
